services:
  datopia-frontend-dev:
    image: amigolli/datopia-frontend-dev:latest
    container_name: datopia-frontend-dev
    ports:
      - "8050:8050"
    networks:
      - datopia-net

networks:
  datopia-net:
    name: datopia-net
    external: true