name: datopia-deploy-frontend-

on:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "public/**"
      - ".github/workflows/datopia-deploy-frontend.yml"
      - "docker-compose-dev.yml"
      - "Dockerfile"

env:
  IMAGE_NAME: datopia-frontend-dev

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Verify SSH Args
        run: |
          echo "Host starts with: $(echo "${{ secrets.VPS_HOST }}" | head -c 4)..."
          echo "Username starts with: $(echo "${{ secrets.VPS_USERNAME }}" | head -c 2)..."

      - name: Copy files to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          port: 22
          password: ${{ secrets.VPS_PASSWORD }}
          source: "docker-compose-dev.yml"
          target: "/home/datopia-frontend-dev"

      #      - name: Create .env file for build vars
      #        run: |
      #          echo "NEXT_PUBLIC_API_BASE_URL=${{ secrets.BACKEND_URL }}" > .env
      #          echo "FRONTEND_URL=${{ secrets.FRONTEND_URL }}" >> .env

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
          build-args: |
            BACKEND_URL=${{ secrets.BACKEND_URL }}
          no-cache: true

  deploy:
    needs: build_and_push
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master

        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          port: 22
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            cd /home/datopia-frontend-dev

            # Docker login
            echo "üîç Logging in to Docker Hub..."
            echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin || { echo "ERROR: Docker Hub login failed";  }
            echo "‚úÖ Docker Hub login successful"

            # Stop and remove old container
            echo "üîç Stopping and removing old container..."
            docker rm -f datopia-frontend-dev || { echo "WARNING: No old container to remove"; }
            echo "‚úÖ Old container removed"

            dangling=$(docker images ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }} -f "dangling=true" -q)
            [ -n "$dangling" ] && docker rmi $dangling
            echo "‚úÖ dangling images cleaned up"

            # Deploy frontend

            # Pull image
            echo "üîç Pulling Docker image..."
            docker compose -f ./docker-compose-dev.yml pull || { echo "ERROR: Failed to pull image";  }
            echo "‚úÖ Image pulled successfully"

            # Start container
            echo "üîç Starting container..."
            docker compose -f ./docker-compose-dev.yml up -d --no-build || { echo "ERROR: Failed to start container";  }
            echo "‚úÖ Container started"

            # Wait & Check
            echo "üîç Waiting for container to stabilize..."
            sleep 10
            echo "üîç Checking container status..."
            docker ps -a | grep datopia-frontend-dev || { echo "ERROR: Container datopia-frontend-dev not running";  }
            echo "‚úÖ Container is running"
            echo "‚úÖ Deployment successful! Visit: ${{ secrets.VPS_URL }}"
